### ISSUE TITLE
I get this deprecation warning message.

### ISSUE THREAD

**Issue by ghiobi** [Project-Epsilon/mobile#28]
`Deprecated: The color input has been removed from HTML elements. Please add the "ion-text" attribute in order to use the color input. For example: "<a ion-text color='secondary'>Link</a>"`

![image](https://cloud.githubusercontent.com/assets/9327403/23773410/139f2610-04ed-11e7-9c69-03673b5c9217.png)

**Comment by Peter0892** [comment]
Fixed this issue. Please check #68
