### ISSUE TITLE
Google login not redirecting back to the app.

### ISSUE THREAD

**Issue by JTalarico** [Project-Epsilon/mobile#70]
When a users tries to sign up using Google+ button, the inappbrowser does not redirect back to the app.

**Comment by ghiobi** [comment]
@ajpower @Scieon @Peter0892 @ronnpang1  Can you confirm?

**Comment by Scieon** [comment]
Issue doesn't occur on my phone.

**Comment by ghost** [comment]
Can confirm that the issue occurs in the browser app. Checking in the mobile app now.

**Comment by ghiobi** [comment]
> The question of whether a computer can think is no more interesting than the question of whether a submarine can swim. - Dijkstra

**Comment by ghiobi** [comment]
EP-135
