### ISSUE TITLE
OTP cannot click send code button

### ISSUE THREAD

**Issue by Scieon** [Project-Epsilon/mobile#78]
'Send Code' Button after entering phone number cannot be selected, hence user cannot sign into application.

**Comment by ghiobi** [comment]
I'm getting these errors in the console.

![image](https://cloud.githubusercontent.com/assets/9327403/24839394/83afae96-1d27-11e7-9048-5bf36902129c.png)

**Comment by ghiobi** [comment]
@ronnpang1 please explain.
